name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - add/github-actions # TODO: remove this after create pull request

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: # see https://github.com/actions/virtual-environments/tree/master/images/macos
          - "11.4"
          - "11.4.1"
          - "11.5_beta"
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - run: swift test